httpEngine:
  addr: ""
  port: ""
  templates: "templates/*"

db:
  Addr: "127.0.0.1"
  Port: "3306"
  User: ""
  Pass: ""
  DB: "test_db"
  DB_MAX_OPEN_CONNS:
  DB_MAX_IDLE_CONNS:
  DB_MAX_LIFETIME_CONNS:

basic:
  jwt:
    secret:

