// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addAtten": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加到关注列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "添加到关注列表",
                "parameters": [
                    {
                        "description": "公司id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JSONid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/attenInfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得关注列表的公司id和状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获得关注列表的公司id和状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CpnListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/company/appeal": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "公司进行申诉",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "公司进行申诉",
                "parameters": [
                    {
                        "description": "公司申诉信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompanyAppealDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/company/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AppealList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/delAtten": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除关注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除关注",
                "parameters": [
                    {
                        "description": "公司id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JSONid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/display": {
            "post": {
                "description": "展示公司及其状态(传入两个索引)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "展示公司及其状态(传入两个索引)",
                "parameters": [
                    {
                        "description": "传入两个索引",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisplayResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/displayBad": {
            "post": {
                "description": "展示可疑公司及其状态(传入两个索引)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "展示可疑公司及其状态(传入两个索引)",
                "parameters": [
                    {
                        "description": "传入两个索引",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisplayResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeAccusStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改待审核的排污实地图列表状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "修改待审核的排污实地图列表状态",
                "parameters": [
                    {
                        "description": "status=1表示不通过,status=2表示等待,status=3表示通过",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AccusStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeAplStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改申诉列表状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "修改申诉列表状态",
                "parameters": [
                    {
                        "description": "status=1表示不通过,status=2表示等待,status=3表示通过",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AplStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "政府修改企业状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "政府修改企业状态",
                "parameters": [
                    {
                        "description": "修改公司状态为status, 1为正常, 2为可疑违规",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Company"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/getAccusationList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有游客投诉信息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "返回所有游客投诉信息列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccusationList"
                        }
                    }
                }
            }
        },
        "/gvmt/getAppealList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AppealList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "运行模型, 得到相关数据和结论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "运行模型, 得到相关数据和结论",
                "parameters": [
                    {
                        "description": "模型运行请求(现在是一些必选项, 后续可以传入自定义的阈值等要求)",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RunModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "运行结果",
                        "schema": {
                            "$ref": "#/definitions/models.RunModelResponse"
                        }
                    }
                }
            }
        },
        "/visitor/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccusationList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/visitor/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "进行举报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "进行举报",
                "parameters": [
                    {
                        "description": "举报信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserPostDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AccusStatusDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "9cade01e-4c66-4c57-910a-2efe5f7e3dff"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Accusation": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "id": {
                    "description": "文章uuid",
                    "type": "string",
                    "example": "a05cde18-488b-4dc4-afa1-df9e0ccf16a1"
                },
                "pic": {
                    "description": "帖子图片路径",
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "description": "帖子内容",
                    "type": "string",
                    "example": "文字内容"
                },
                "status": {
                    "description": "举报状态",
                    "type": "integer",
                    "example": 2
                },
                "time": {
                    "description": "时间",
                    "type": "string",
                    "example": "2022-01-28T23:57:30+08:00"
                },
                "userId": {
                    "description": "用户名",
                    "type": "string",
                    "example": "123123"
                }
            }
        },
        "models.AccusationList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Accusation"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.AplStatusDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "967d7ae4-1c39-40f8-befd-222d768d70f7"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Appeal": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "id": {
                    "description": "文章uuid",
                    "type": "string",
                    "example": "967d7ae4-1c39-40f8-befd-222d768d70f7"
                },
                "pic": {
                    "description": "帖子图片路径",
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "description": "帖子内容",
                    "type": "string",
                    "example": "文字内容"
                },
                "status": {
                    "description": "举报状态",
                    "type": "integer",
                    "example": 2
                },
                "time": {
                    "description": "时间",
                    "type": "string",
                    "example": "2022-01-28T23:45:54+08:00"
                }
            }
        },
        "models.AppealList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Appeal"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "172800010800110000"
                },
                "status": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.CompanyAppealDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "pic": {
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "type": "string",
                    "example": "文字申诉内容"
                }
            }
        },
        "models.CpnListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Company"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.DisplayRequest": {
            "type": "object",
            "properties": {
                "idx1": {
                    "type": "string",
                    "example": "1"
                },
                "idx2": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "models.DisplayResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Company"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.FailureResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "401"
                },
                "msg": {
                    "type": "string",
                    "example": "token invalid"
                }
            }
        },
        "models.JSONid": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "账号",
                    "type": "string",
                    "example": "321321"
                },
                "pwd": {
                    "description": "密码",
                    "type": "string",
                    "example": "321"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MjgwMDAwMDg5OSIsImlhdCI6MTU4NjQwMjQ5NywiZXhwIjoxNTg2NDAyNzk3fQ."
                }
            }
        },
        "models.RunModelRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "description": "公司ID",
                    "type": "string",
                    "example": "17280000089583"
                },
                "date_e_1": {
                    "description": "日/月/年,当前结束时间",
                    "type": "string",
                    "example": "1/2/2020"
                },
                "date_e_2": {
                    "description": "日/月/年,对照数据结束时间",
                    "type": "string",
                    "example": "1/4/2020"
                },
                "date_s_1": {
                    "description": "日/月/年,当前开始时间",
                    "type": "string",
                    "example": "1/1/2020"
                },
                "date_s_2": {
                    "description": "日/月/年,对照数据开始时间",
                    "type": "string",
                    "example": "1/3/2020"
                },
                "polution_id": {
                    "description": "污染物ID",
                    "type": "string",
                    "example": "w00000"
                },
                "port_id": {
                    "description": "污染口ID",
                    "type": "string",
                    "example": "64000000000600100000"
                },
                "threshold": {
                    "description": "阈值",
                    "type": "string",
                    "example": "100"
                }
            }
        },
        "models.RunModelRespData": {
            "type": "object",
            "properties": {
                "average_amount": {
                    "description": "平均量",
                    "type": "number",
                    "example": 100
                },
                "average_concentration": {
                    "description": "平均浓度",
                    "type": "number",
                    "example": 0.2
                },
                "compare_other_change": {
                    "description": "相对对照数据的变化",
                    "type": "number",
                    "example": 0.2
                },
                "compare_other_change_rate": {
                    "description": "相对对照数据的变化率",
                    "type": "number",
                    "example": 0.2
                },
                "compare_other_num": {
                    "description": "对照其他公司天数",
                    "type": "integer",
                    "example": 1
                },
                "compare_threshold": {
                    "description": "较阈值",
                    "type": "number",
                    "example": -0.2
                },
                "compared_data_average_amount": {
                    "description": "如 上周平均量",
                    "type": "number",
                    "example": 100
                },
                "compared_data_average_concentration": {
                    "description": "如 上周平均浓度",
                    "type": "number",
                    "example": 2.5
                },
                "danger_num": {
                    "description": "疑似违规天数",
                    "type": "integer",
                    "example": 1
                },
                "danger_polution_num": {
                    "description": "对该污染物的疑似违规天数",
                    "type": "integer",
                    "example": 1
                },
                "port_amount": {
                    "description": "该排污口排污量",
                    "type": "number",
                    "example": 1000
                },
                "port_concentration": {
                    "description": "平均排污浓度",
                    "type": "number",
                    "example": 3.5
                },
                "port_id": {
                    "description": "污染口ID",
                    "type": "string",
                    "example": "64000000000600100000"
                },
                "port_relative_cpn": {
                    "description": "其他共用企业id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "123",
                        " 456",
                        " 789"
                    ]
                }
            }
        },
        "models.RunModelResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "$ref": "#/definitions/models.RunModelRespData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.UserPostDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "pic": {
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "type": "string",
                    "example": "文字内容"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
