// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addAtten": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加到关注列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "添加到关注列表",
                "parameters": [
                    {
                        "description": "公司id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JSONid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/attenInfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获得关注列表的公司id和状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获得关注列表的公司id和状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CpnListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/company/appeal": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "公司进行申诉",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "公司进行申诉",
                "parameters": [
                    {
                        "description": "公司申诉信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompanyAppealDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/company/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AppealList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/delAtten": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除关注",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除关注",
                "parameters": [
                    {
                        "description": "公司id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JSONid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/display": {
            "post": {
                "description": "展示公司及其状态(传入两个索引)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "展示公司及其状态(传入两个索引)",
                "parameters": [
                    {
                        "description": "传入两个索引",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisplayResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/displayBad": {
            "post": {
                "description": "展示可疑公司及其状态(传入两个索引)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "展示可疑公司及其状态(传入两个索引)",
                "parameters": [
                    {
                        "description": "传入两个索引(降序黑榜)",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisplayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisplayResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeAccusStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改待审核的排污实地图列表状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "修改待审核的排污实地图列表状态",
                "parameters": [
                    {
                        "description": "status=1表示不通过,status=2表示等待,status=3表示通过",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AccusStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeAplStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改申诉列表状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "修改申诉列表状态",
                "parameters": [
                    {
                        "description": "status=1表示不通过,status=2表示等待,status=3表示通过",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AplStatusDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/changeStatus": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "政府修改企业状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "政府修改企业状态",
                "parameters": [
                    {
                        "description": "修改公司状态为status, 1为正常, 2为可疑违规(改: 1为减一次, 2为加一次, 3为归零)",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Company"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/gvmt/getAccusationList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有游客投诉信息列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "返回所有游客投诉信息列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccusationList"
                        }
                    }
                }
            }
        },
        "/gvmt/getAppealList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gvmt(admin)"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AppealList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "post": {
                "description": "获得企业的port_id和polution_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获得企业的port_id和polution_id",
                "parameters": [
                    {
                        "description": "企业id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.InfoResp"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "运行模型, 得到相关数据和结论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "运行模型, 得到相关数据和结论",
                "parameters": [
                    {
                        "description": "模型运行请求(现在是一些必选项, 后续可以传入自定义的阈值等要求)",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RunModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "运行结果",
                        "schema": {
                            "$ref": "#/definitions/models.RunModelResponse"
                        }
                    }
                }
            }
        },
        "/visitor/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有的企业申诉信息给政府视图",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "返回所有的企业申诉信息给政府视图",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AccusationList"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        },
        "/visitor/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "进行举报",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "visitor"
                ],
                "summary": "进行举报",
                "parameters": [
                    {
                        "description": "举报信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserPostDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.FailureResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AccusStatusDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "9cade01e-4c66-4c57-910a-2efe5f7e3dff"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Accusation": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "id": {
                    "description": "文章uuid",
                    "type": "string",
                    "example": "a05cde18-488b-4dc4-afa1-df9e0ccf16a1"
                },
                "pic": {
                    "description": "帖子图片路径",
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "description": "帖子内容",
                    "type": "string",
                    "example": "文字内容"
                },
                "status": {
                    "description": "举报状态",
                    "type": "integer",
                    "example": 2
                },
                "time": {
                    "description": "时间",
                    "type": "string",
                    "example": "2022-01-28T23:57:30+08:00"
                },
                "userId": {
                    "description": "用户名",
                    "type": "string",
                    "example": "123123"
                }
            }
        },
        "models.AccusationList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Accusation"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.AplStatusDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "967d7ae4-1c39-40f8-befd-222d768d70f7"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Appeal": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "id": {
                    "description": "文章uuid",
                    "type": "string",
                    "example": "967d7ae4-1c39-40f8-befd-222d768d70f7"
                },
                "pic": {
                    "description": "帖子图片路径",
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "description": "帖子内容",
                    "type": "string",
                    "example": "文字内容"
                },
                "status": {
                    "description": "举报状态",
                    "type": "integer",
                    "example": 2
                },
                "time": {
                    "description": "时间",
                    "type": "string",
                    "example": "2022-01-28T23:45:54+08:00"
                }
            }
        },
        "models.AppealList": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Appeal"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Company": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "172800010800110000"
                },
                "status": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "models.CompanyAppealDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "pic": {
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "type": "string",
                    "example": "文字申诉内容"
                }
            }
        },
        "models.CpnListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Company"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.DataModel": {
            "type": "object",
            "properties": {
                "average_amount": {
                    "description": "平均排污量",
                    "type": "number",
                    "example": 2127.598713285988
                },
                "average_concentration": {
                    "description": "平均浓度",
                    "type": "number",
                    "example": 52.787238479217876
                },
                "data1_compare_data2_with_average_amount_loss": {
                    "description": "较[上周]排污量增长量",
                    "type": "number",
                    "example": 51.1888359508704
                },
                "data1_compare_data2_with_average_amount_loss_rate": {
                    "description": "较[上周]排污量增长率",
                    "type": "number",
                    "example": -0.8009344011185189
                },
                "data1_compare_data2_with_average_concentration_loss": {
                    "description": "较[上周]浓度增长量",
                    "type": "number",
                    "example": -13.094681522291124
                },
                "data1_compare_data2_with_average_concentration_loss_rate": {
                    "description": "较[上周]浓度增长率",
                    "type": "number",
                    "example": -0.8279401442320188
                },
                "date1_amount_test_list": {
                    "description": "模型重构排放量序列",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        1853.283905720711,
                        1853.283905720711,
                        314.8520582050088
                    ]
                },
                "date1_amount_truth_list": {
                    "description": "原始采集排放量数据",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        870.0000334143641,
                        1757.9999680727722,
                        1917.9999588906767
                    ]
                },
                "date1_amount_warning_tags": {
                    "description": "排放量异常日期列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "2020-01-07'",
                        " '2020-01-08'"
                    ]
                },
                "date1_amount_warning_tags_count": {
                    "description": "排放量异常日期数量",
                    "type": "integer",
                    "example": 1
                },
                "date1_compare_amount_loss_with_threshold": {
                    "description": "平均排放量异常指数较阈值",
                    "type": "number",
                    "example": -2375.351830534637
                },
                "date1_compare_concentration_loss_with_threshold": {
                    "description": "平均浓度异常指数较阈值",
                    "type": "number",
                    "example": -199.19129530233997
                },
                "date1_concentration_test_list": {
                    "description": "模型重构浓度序列",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        90.42889326810837,
                        90.42889326810837,
                        71.88690975308418
                    ]
                },
                "date1_concentration_truth_list": {
                    "description": "原始采集浓度数据",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        66.25000024214387,
                        73.17999936640263
                    ]
                },
                "date1_concentration_warning_tags": {
                    "description": "浓度异常日期列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "'2020-01-07'",
                        " '2020-01-08'"
                    ]
                },
                "date1_concentration_warning_tags_count": {
                    "description": "浓度异常日期数量",
                    "type": "integer",
                    "example": 1
                },
                "date2_amount_truth_list": {
                    "description": "[上周]原始采集排放量数据",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        870.0000334143641,
                        1757.9999680727722,
                        1917.9999588906767
                    ]
                },
                "date2_average_amount_truth": {
                    "description": "[上周]平均排污量",
                    "type": "number",
                    "example": 2127.598713285988
                },
                "date2_average_concentration_truth": {
                    "description": "[上周]平均浓度",
                    "type": "number",
                    "example": 52.787238479217876
                },
                "date2_concentration_truth_list": {
                    "description": "[上周]原始采集浓度数据",
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        66.25000024214387,
                        73.17999936640263
                    ]
                },
                "polution_id": {
                    "description": "污染物ID",
                    "type": "string",
                    "example": "w00000"
                },
                "port_average_amount": {
                    "description": "排放口平均排污量",
                    "type": "number",
                    "example": 2127.598713285988
                },
                "port_total_concentration": {
                    "description": "排放口总浓度",
                    "type": "number",
                    "example": 61295.512913
                },
                "relative_cpn": {
                    "description": "排放口关联公司",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "123",
                        "456",
                        "789"
                    ]
                }
            }
        },
        "models.DisplayRequest": {
            "type": "object",
            "properties": {
                "idx1": {
                    "type": "string",
                    "example": "1"
                },
                "idx2": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "models.DisplayResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Company"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.FailureResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "401"
                },
                "msg": {
                    "type": "string",
                    "example": "token invalid"
                }
            }
        },
        "models.InfoReq": {
            "type": "object",
            "properties": {
                "company_id": {
                    "description": "公司ID",
                    "type": "string",
                    "example": "17280000089583"
                }
            }
        },
        "models.InfoResp": {
            "type": "object",
            "properties": {
                "polution_ids": {
                    "description": "污染物ID",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "w00000",
                        "w00001",
                        "w00010"
                    ]
                },
                "port_ids": {
                    "description": "排污口ID",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "64000000000600100000",
                        "64000000000600100000",
                        "64000000000600100000"
                    ]
                }
            }
        },
        "models.JSONid": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "账号",
                    "type": "string",
                    "example": "321321"
                },
                "pwd": {
                    "description": "密码",
                    "type": "string",
                    "example": "321"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MjgwMDAwMDg5OSIsImlhdCI6MTU4NjQwMjQ5NywiZXhwIjoxNTg2NDAyNzk3fQ."
                }
            }
        },
        "models.OverviewModel": {
            "type": "object",
            "properties": {
                "compare_total_amount_warning_count": {
                    "description": "较[上周] 总览排放量异常次数增加",
                    "type": "integer",
                    "example": 1
                },
                "compare_total_amount_warning_count_rate": {
                    "description": "较[上周] 总览排放量异常次数增加率, 如果为-1,则表明[上周]排放量没有异常",
                    "type": "number",
                    "example": -0.8279401442320188
                },
                "compare_total_concentration_warning_count": {
                    "description": "较[上周] 总览浓度异常次数增加",
                    "type": "integer",
                    "example": 1
                },
                "compare_total_concentration_warning_count_rate": {
                    "description": "较[上周] 总览浓度异常次数增加率, 如果为-1,则表明[上周]浓度没有异常",
                    "type": "number",
                    "example": -0.8279401442320188
                },
                "compare_total_warning_count": {
                    "description": "较[上周] 总览排放量和浓度异常次数增加",
                    "type": "integer",
                    "example": 1
                },
                "compare_total_warning_count_rate": {
                    "description": "较[上周] 总览排放量和浓度异常次数增加率",
                    "type": "number",
                    "example": -0.8279401442320188
                },
                "date1_total_amount_warning_count": {
                    "description": "[本周] 总览排放量异常次数",
                    "type": "integer",
                    "example": 1
                },
                "date1_total_concentration_warning_count": {
                    "description": "[本周] 总览浓度异常次数",
                    "type": "integer",
                    "example": 1
                },
                "date1_total_warning_count": {
                    "description": "[本周] 总览浓度与排放量异常总次数",
                    "type": "integer",
                    "example": 1
                },
                "date2_total_amount_warning_count": {
                    "description": "[上周] 总览排放量异常次数",
                    "type": "integer",
                    "example": 1
                },
                "date2_total_concentration_warning_count": {
                    "description": "[上周] 总览浓度异常次数",
                    "type": "integer",
                    "example": 1
                },
                "date2_total_warning_count": {
                    "description": "[上周] 总览浓度与排放量异常总次数",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.RunModelRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "description": "公司ID",
                    "type": "string",
                    "example": "17280000089583"
                },
                "date_e_1": {
                    "description": "日/月/年,当前结束时间",
                    "type": "string",
                    "example": "1/2/2020"
                },
                "date_e_2": {
                    "description": "日/月/年,对照数据结束时间",
                    "type": "string",
                    "example": "1/4/2020"
                },
                "date_s_1": {
                    "description": "日/月/年,当前开始时间",
                    "type": "string",
                    "example": "1/1/2020"
                },
                "date_s_2": {
                    "description": "日/月/年,对照数据开始时间",
                    "type": "string",
                    "example": "1/3/2020"
                },
                "polution_id": {
                    "description": "污染物ID",
                    "type": "string",
                    "example": "w00000"
                },
                "port_id": {
                    "description": "污染口ID",
                    "type": "string",
                    "example": "64000000000600100000"
                },
                "threshold_amount_loss": {
                    "description": "排放量损失阈值",
                    "type": "number",
                    "example": 2000.1
                },
                "threshold_concentration_loss": {
                    "description": "浓度损失阈值",
                    "type": "number",
                    "example": 200.1
                }
            }
        },
        "models.RunModelRespData": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "description": "单个污染物视图下的相关数据",
                    "$ref": "#/definitions/models.DataModel"
                },
                "meta": {
                    "description": "single为单个污染物模式, all为总览模式",
                    "type": "string",
                    "example": "single"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                },
                "overview": {
                    "description": "总览视图下的相关数据",
                    "$ref": "#/definitions/models.OverviewModel"
                }
            }
        },
        "models.RunModelResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "data": {
                    "$ref": "#/definitions/models.RunModelRespData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.UserPostDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "17280000089799"
                },
                "pic": {
                    "type": "string",
                    "example": "图片内容"
                },
                "post": {
                    "type": "string",
                    "example": "文字内容"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
